config/routes.rb
Rails.application.routes.draw do
  resources :disciplinas
  resources :testes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "menu#root"
  
  get "/teste", to: "menu#teste"
  get "/numero/:x/outro/:y", to: "menu#numero"
  get "/cond/:nome", to: "pagina#cond"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/disciplina.rb
class Disciplina < ApplicationRecord
end

app/models/teste.rb
class Teste < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/disciplinas_controller.rb
class DisciplinasController < ApplicationController
  before_action :set_disciplina, only: [:show, :edit, :update, :destroy]

  # GET /disciplinas
  # GET /disciplinas.json
  def index
    @disciplinas = Disciplina.all
  end

  # GET /disciplinas/1
  # GET /disciplinas/1.json
  def show
  end

  # GET /disciplinas/new
  def new
    @disciplina = Disciplina.new
  end

  # GET /disciplinas/1/edit
  def edit
  end

  # POST /disciplinas
  # POST /disciplinas.json
  def create
    @disciplina = Disciplina.new(disciplina_params)

    respond_to do |format|
      if @disciplina.save
        format.html { redirect_to @disciplina, notice: 'Disciplina was successfully created.' }
        format.json { render :show, status: :created, location: @disciplina }
      else
        format.html { render :new }
        format.json { render json: @disciplina.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplinas/1
  # PATCH/PUT /disciplinas/1.json
  def update
    respond_to do |format|
      if @disciplina.update(disciplina_params)
        format.html { redirect_to @disciplina, notice: 'Disciplina was successfully updated.' }
        format.json { render :show, status: :ok, location: @disciplina }
      else
        format.html { render :edit }
        format.json { render json: @disciplina.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplinas/1
  # DELETE /disciplinas/1.json
  def destroy
    @disciplina.destroy
    respond_to do |format|
      format.html { redirect_to disciplinas_url, notice: 'Disciplina was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disciplina
      @disciplina = Disciplina.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disciplina_params
      params.require(:disciplina).permit(:nome, :carga)
    end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
    
    def teste
    end
    
    def root
    end
    
    def numero
        # Atribui o var ao valor interno de x
        @var  = params[:x]
        @var2 = params[:y]
    end
end

app/controllers/pagina_controller.rb
class PaginaController < ApplicationController

    def cond
       @condicional = params[:nome]
    end
end

app/controllers/testes_controller.rb
class TestesController < ApplicationController
  before_action :set_testis, only: [:show, :edit, :update, :destroy]

  # GET /testes
  # GET /testes.json
  def index
    @testes = Teste.all
  end

  # GET /testes/1
  # GET /testes/1.json
  def show
  end

  # GET /testes/new
  def new
    @testis = Teste.new
  end

  # GET /testes/1/edit
  def edit
  end

  # POST /testes
  # POST /testes.json
  def create
    @testis = Teste.new(testis_params)

    respond_to do |format|
      if @testis.save
        format.html { redirect_to @testis, notice: 'Teste was successfully created.' }
        format.json { render :show, status: :created, location: @testis }
      else
        format.html { render :new }
        format.json { render json: @testis.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testes/1
  # PATCH/PUT /testes/1.json
  def update
    respond_to do |format|
      if @testis.update(testis_params)
        format.html { redirect_to @testis, notice: 'Teste was successfully updated.' }
        format.json { render :show, status: :ok, location: @testis }
      else
        format.html { render :edit }
        format.json { render json: @testis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testes/1
  # DELETE /testes/1.json
  def destroy
    @testis.destroy
    respond_to do |format|
      format.html { redirect_to testes_url, notice: 'Teste was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testis
      @testis = Teste.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testis_params
      params.require(:testes).permit(:nome)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/disciplinas_helper.rb
module DisciplinasHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/pagina_helper.rb
module PaginaHelper
end

app/helpers/testes_helper.rb
module TestesHelper
end

app/views/disciplinas/_form.html.erb
<%= form_for(disciplina) do |f| %>
  <% if disciplina.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(disciplina.errors.count, "error") %> prohibited this disciplina from being saved:</h2>

      <ul>
      <% disciplina.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :carga %>
    <%= f.text_field :carga %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/disciplinas/edit.html.erb
<h1>Editing Disciplina</h1>

<%= render 'form', disciplina: @disciplina %>

<%= link_to 'Show', @disciplina %> |
<%= link_to 'Back', disciplinas_path %>

app/views/disciplinas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Disciplinas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Carga</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @disciplinas.each do |disciplina| %>
      <tr>
        <td><%= disciplina.nome %></td>
        <td><%= disciplina.carga %></td>
        <td><%= link_to 'Show', disciplina %></td>
        <td><%= link_to 'Edit', edit_disciplina_path(disciplina) %></td>
        <td><%= link_to 'Destroy', disciplina, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Disciplina', new_disciplina_path %>

app/views/disciplinas/new.html.erb
<h1>New Disciplina</h1>

<%= render 'form', disciplina: @disciplina %>

<%= link_to 'Back', disciplinas_path %>

app/views/disciplinas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @disciplina.nome %>
</p>

<p>
  <strong>Carga:</strong>
  <%= @disciplina.carga %>
</p>

<%= link_to 'Edit', edit_disciplina_path(@disciplina) %> |
<%= link_to 'Back', disciplinas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projeto</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/menu/numero.html.erb
<div>
    <h3 stlye="color: red">
        Esse número é: <%= @var %>
    </h3>
</div>

app/views/menu/root.html.erb
<h2 style="color:#122211; font-weight: bold">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure, inventore.</h2>

app/views/menu/teste.html.erb
<h1>Pega no meu mundo</h1>

app/views/pagina/cond.html.erb
<% if @condicional == "" then %>
    <h1>
        Olá visitante
    </h1>
<% else %>
    <h1>
        Olá <%= @condicional %>
    </h1>
<% end %>
 

app/views/testes/_form.html.erb
<%= form_for(testis) do |f| %>
  <% if testis.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(testis.errors.count, "error") %> prohibited this testis from being saved:</h2>

      <ul>
      <% testis.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label : %>
    <%= f.text_field : %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/testes/edit.html.erb
<h1>Editing Testis</h1>

<%= render 'form', testis: @testis %>

<%= link_to 'Show', @testis %> |
<%= link_to 'Back', testes_path %>

app/views/testes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Testes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @testes.each do |testis| %>
      <tr>
        <td><%= testis.nome %></td>
        <td><%= testis. %></td>
        <td><%= link_to 'Show', testis %></td>
        <td><%= link_to 'Edit', edit_testis_path(testis) %></td>
        <td><%= link_to 'Destroy', testis, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Testis', new_testis_path %>

app/views/testes/new.html.erb
<h1>New Testis</h1>

<%= render 'form', testis: @testis %>

<%= link_to 'Back', testes_path %>

app/views/testes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @testis.nome %>
</p>

<p>
  <strong>:</strong>
  <%= @testis. %>
</p>

<%= link_to 'Edit', edit_testis_path(@testis) %> |
<%= link_to 'Back', testes_path %>